updated build

diff --git a/build/d/gcc/build_gcc-pre b/build/d/gcc/build_gcc-pre
--- a/build/d/gcc/build_gcc-pre
+++ b/build/d/gcc/build_gcc-pre
@@ -26,8 +26,21 @@ case $(uname -m) in
 		find /tools/opt/gnat -name ld -exec as -v {} {}.old \;
 		echo ;;
 	*)
-		upgradepkg --install-new /source/others/gcc-gnat-10.3.0-i586-2.txz ;;
+#		if ! tar xf /source/others/gnat-gpl-2014-x86-linux-bin.tar.gz; then
+#			echo
+#			echo "Tar extraction of gnat-gpl-2014-x86-linux-bin failed."
+#			echo && exit 1
+#		fi
+#		cd gnat-gpl-2014-x86-linux-bin || exit 1 ;;
+		source /source/d/gcc/execute_sed_gcc ;;
 esac
+
+#mkdir -pv /tools/opt/gnat
+#make ins-all prefix=/tools/opt/gnat
+#PATH_HOLD=$PATH && export PATH=/tools/opt/gnat/bin:$PATH_HOLD
+#echo "$PATH"
+#find /tools/opt/gnat -name ld -exec mv -v {} {}.old \;
+#find /tools/opt/gnat -name ld -exec as -v {} {}.old \;
 
 cd /scripts || exit 1
 }
